### ISSUE TITLE
skaffold binary storage url changed

### ISSUE THREAD

**Issue by joprice** [nklmilojevic/asdf-skaffold#1]
The latest version of skaffold in github does not have attached assets. I am new to the tool, but I see that the docs here list a different url: https://skaffold.dev/docs/install/. I can install versions up to 1.36.0, but when trying the latest 1.35.1, I get the following error:

```
curl: (22) The requested URL returned error: 404
asdf-skaffold: Could not download https://github.com/GoogleContainerTools/skaffold/releases/download/v1.36.1/skaffold-darwin-amd64
```

**Comment by nklmilojevic** [comment]
@joprice will take a look at it, thanks for reporting!

**Comment by nklmilojevic** [comment]
hey @joprice I will keep the issue opened, but seems that they forgot to upload the asset to GitHub:

https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.36.1

Other releases have assets, and seems that there was an exception in the latest one. I will see to make a smart way to always query their storage rather than GitHub and let you know.

**Comment by nklmilojevic** [comment]
Ok found a way, fixed in https://github.com/nklmilojevic/asdf-skaffold/pull/2, please update your plugin (`asdf plugin update --all`)

**Comment by joprice** [comment]
Works! Thank you for the quick fix!
